services:
  - type: web
    name: cineranks
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - fromDatabase:
          name: cineranks-db
          property: connectionString  # Auto DATABASE_URL interna
  - type: postgres  # Â¡FIX: postgres, NO pgsql!
    name: cineranks-db
    plan: starter
