services:
  - type: web
    name: cineranks
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TMDB_API_KEY
        sync: false  # AÃ±ade tu key manual
      - fromDatabase:
          name: cineranks-db
          property: connectionString  # Auto DATABASE_URL interna
    autoDeploy: true
  - type: pgsql
    name: cineranks-db
    plan: starter  # 1GB storage, autoscaling
